import moment from "moment"
import { CustomColumnType } from "@components/smartTable/lib/types"
import { Bank } from "../models"

const getBanksColumns = (): CustomColumnType<Bank>[] => ([
    {
        title: 'Название',
        dataIndex: 'name',
        key: 'name',
        customFilter: 'search',
        sorter: (a, b) => a.name.localeCompare(b.name),
        editable: true,
        width: 300,
    },
    {
        title: 'БИК',
        dataIndex: 'BIK',
        key: 'BIK',
        customFilter: 'search',
        align: 'center',
        sorter: (a, b) => a.BIK.localeCompare(b.BIK),
        editable: true,
        width: 150,
    },
    {
        title: 'ИНН',
        dataIndex: 'INN',
        key: 'INN',
        customFilter: 'search',
        align: 'center',
        sorter: (a, b) => a.INN.localeCompare(b.INN),
        editable: true,
        width: 150,
    },
    {
        title: 'Дневной лимит',
        dataIndex: 'dayLimit',
        key: 'dayLimit',
        customFilter: 'slider',
        align: 'center',
        sorter: (a, b) => a.dayLimit - b.dayLimit,
        editable: true,
        editType: 'number',
        width: 150,
    },
    {
        title: 'Месячный лимит',
        dataIndex: 'monthLimit',
        key: 'monthLimit',
        customFilter: 'slider',
        align: 'center',
        sorter: (a, b) => a.monthLimit - b.monthLimit,
        editable: true,
        editType: 'number',
        width: 150,
    },
    {
        title: 'Корреспондентский счет',
        dataIndex: 'cor_account',
        key: 'cor_account',
        customFilter: 'search',
        align: 'center',
        sorter: (a, b) => a.cor_account.localeCompare(b.cor_account),
        editable: true,
        width: 200,
    },
    {
        title: 'Кем создано',
        dataIndex: ['created_by', 'name'],
        key: 'created_by',
        customFilter: 'search',
        align: 'center',
        sorter: (a, b) => a.created_by.name.localeCompare(b.created_by.name),
        width: 150,
        responsive: ['xl'],
        editable: false,
    },
    {
        title: 'Когда создано',
        dataIndex: 'created_date',
        key: 'created_date',
        customFilter: 'date-picker',
        render: (value) => (!!value ? moment(value).format('L') : '-'),
        sorter: (a, b) => moment(a.created_date).diff(b.created_date),
        align: 'center',
        width: 150,
        responsive: ['xl'],
        editable: false,
    },
    {
        title: 'Кем изменено',
        dataIndex: ['updated_by', 'name'],
        key: 'updated_by',
        customFilter: 'search',
        align: 'center',
        sorter: (a, b) => a.updated_by?.name.localeCompare(b.updated_by?.name ?? '') ?? 0,
        render: (value) => value ?? '-',
        width: 150,
        responsive: ['xxl'],
        editable: false,
    },
    {
        title: 'Когда изменено',
        dataIndex: 'updated_date',
        key: 'updated_date',
        customFilter: 'date-picker',
        render: (value) => (!!value ? moment(value).format('L LT') : '-'),
        sorter: (a, b) => moment(a.updated_date).diff(b.updated_date),
        align: 'center',
        width: 150,
        responsive: ['xxl'],
        editable: false,
    },
])

export default getBanksColumns